const option = [{
  value: '1',
  label: '土建',
  children: [{
    value: '12',
    label: '金属材料',
    children: [{
      value: '36',
      label: '热轧圆盘条'
    }, {
      value: '37',
      label: '螺纹钢筋'
    }, {
      value: '38',
      label: '冷轧带肋钢筋'
    }, {
      value: '39',
      label: '冷轧牛扭钢筋'
    }, {
      value: '40',
      label: '圆钢'
    }, {
      value: '41',
      label: '方钢'
    }, {
      value: '42',
      label: '扇钢'
    }, {
      value: '43',
      label: '工字钢'
    }, {
      value: '44',
      label: '钢板'
    }, {
      value: '45',
      label: 'H型钢'
    }, {
      value: '46',
      label: '槽钢'
    }, {
      value: '47',
      label: '角钢'
    }, {
      value: '48',
      label: '其他金属材料'
    }, {
      value: '49',
      label: '光圆钢筋'
    }
    ]
  }, {
    value: '13',
    label: '砼、砂浆及其他配合比材料',
    children: [{
      value: '50',
      label: '水泥砂浆'
    }, {
      value: '51',
      label: '混合砂浆'
    }, {
      value: '52',
      label: '特种砂浆'
    }, {
      value: '53',
      label: '胶泥、脂、油'
    }, {
      value: '54',
      label: '特种混凝土'
    }, {
      value: '55',
      label: '轻质混凝土'
    }, {
      value: '56',
      label: '水泥混凝土'
    }, {
      value: '57',
      label: '其他砂浆(石灰砂浆)'
    }
    ]
  }, {
    value: '14',
    label: '模板材料及工具',
    children: [{
      value: '58',
      label: '模板'
    }, {
      value: '59',
      label: '脚手架'
    }, {
      value: '60',
      label: '脚手架配件'
    }, {
      value: '61',
      label: '活动板房'
    }]
  }, {
    value: '15',
    label: '水泥砖瓦',
    children: [{
      value: '62',
      label: '水泥'
    }, {
      value: '63',
      label: '砌砖'
    }, {
      value: '64',
      label: '砌块'
    }, {
      value: '65',
      label: '瓦'
    }, {
      value: '66',
      label: '石子'
    }, {
      value: '67',
      label: '轻骨料'
    }, {
      value: '68',
      label: '砂'
    }, {
      value: '69',
      label: '灰、粉、土登掺和填充料'
    }]
  }, {
    value: '16',
    label: '绝热、耐火材料',
    children: [{
      value: '70',
      label: '岩棉保湿制品'
    }, {
      value: '71',
      label: '挤箜板'
    }, {
      value: '72',
      label: '橡塑保温制品'
    }, {
      value: '73',
      label: '矿渣棉及其制品'
    }, {
      value: '74',
      label: '其他保温耐火材料'
    }, {
      value: '75',
      label: '耐火砖'
    }, {
      value: '76',
      label: '聚苯板'
    }, {
      value: '77',
      label: '聚氨酯泡沫'
    }, {
      value: '78',
      label: '玻璃棉保温制品'
    }]
  }, {
    value: '17',
    label: '建筑五金',
    children: [{
      value: '79',
      label: '螺栓'
    }, {
      value: '80',
      label: '螺柱'
    }, {
      value: '81',
      label: '高强螺栓'
    }, {
      value: '82',
      label: '膨胀螺栓'
    }, {
      value: '83',
      label: '螺母'
    }, {
      value: '84',
      label: '螺钉'
    }, {
      value: '85',
      label: '铆钉'
    }, {
      value: '86',
      label: '普通钉类'
    }, {
      value: '87',
      label: '挡圈'
    }, {
      value: '88',
      label: '键'
    }, {
      value: '89',
      label: '销'
    }, {
      value: '90',
      label: '垫圈'
    }, {
      value: '91',
      label: '门锁'
    }, {
      value: '92',
      label: '升降器'
    }, {
      value: '93',
      label: '其他门窗五金'
    }, {
      value: '94',
      label: '钢筋锚具、接头'
    }, {
      value: '95',
      label: '铁件(止水钢板)'
    }
    ]
  }, {
    value: '18',
    label: '防水材料',
    children: [{
      value: '96',
      label: '防水涂料'
    }, {
      value: '97',
      label: '沥青防水卷材'
    }, {
      value: '98',
      label: '其他防水卷材'
    }, {
      value: '99',
      label: '耐酸砖、板'
    }, {
      value: '100',
      label: '防水辅材'
    }, {
      value: '101',
      label: '止水材料'
    }
    ]
  }, {
    value: '19',
    label: '电极及其他材料',
    children: [{
      value: '102',
      label: '零星施工用料'
    }, {
      value: '103',
      label: '水、电、煤炭、火柴'
    }]
  }, {
    value: '20',
    label: '新型材料',
    children: [{
      value: '104',
      label: '密肋楼盖'
    }, {
      value: '105',
      label: '建筑模壳'
    }, {
      value: '106',
      label: '混凝土空心薄壁箱'
    }, {
      value: '107',
      label: '空心楼盖填充芯楼'
    }, {
      value: '108',
      label: '空心楼盖聚苯填充体芯模'
    }, {
      value: '109',
      label: '剧本填充管'
    }, {
      value: '110',
      label: '水泥薄壁管'
    }, {
      value: '111',
      label: 'BDF/BBF无机阻燃复合箱体'
    }
    ]
  }]
}, {
  value: '2',
  label: '装饰',
  children: [{
    value: '21',
    label: '橡胶、塑料及金属材料',
    children: [{
      value: '112',
      label: '塑料条带'
    }, {
      value: '113',
      label: '螺纹钢筋'
    }, {
      value: '114',
      label: '冷轧带肋钢筋'
    }, {
      value: '115',
      label: '冷轧牛扭钢筋'
    }, {
      value: '116',
      label: '圆钢'
    }, {
      value: '117',
      label: '方钢'
    }, {
      value: '118',
      label: '扇钢'
    }, {
      value: '119',
      label: '工字钢'
    }, {
      value: '120',
      label: '钢板'
    }, {
      value: '121',
      label: 'H型钢'
    }, {
      value: '122',
      label: '槽钢'
    }, {
      value: '123',
      label: '角钢'
    }, {
      value: '124',
      label: '其他金属材料'
    }, {
      value: '125',
      label: '光圆钢筋'
    }]
  }, {
    value: '22',
    label: '木、竹材料及其制品',
    children: [{
      value: '126',
      label: '原木'
    }, {
      value: '127',
      label: '锯材'
    }]
  }, {
    value: '23',
    label: '玻璃、及玻璃制品',
    children: [{
      value: '128',
      label: '平板玻璃'
    }, {
      value: '129',
      label: '钢化玻璃'
    }, {
      value: '130',
      label: '夹层玻璃'
    }, {
      value: '131',
      label: '中空玻璃'
    }, {
      value: '132',
      label: '镜面玻璃'
    }, {
      value: '133',
      label: '玻璃砖'
    }, {
      value: '134',
      label: '玻璃制品'
    }, {
      value: '135',
      label: '夹丝玻璃'
    }, {
      value: '136',
      label: '特种玻璃'
    }, {
      value: '137',
      label: '彩色玻璃'
    }, {
      value: '138',
      label: '镀膜玻璃'
    }, {
      value: '139',
      label: '工艺玻璃'
    }]
  }, {
    value: '24',
    label: '门窗幕墙',
    children: [{
      value: '140',
      label: '木门'
    }, {
      value: '141',
      label: '玻璃门'
    }, {
      value: '142',
      label: '旋转门自动门'
    }, {
      value: '143',
      label: '防火门'
    }, {
      value: '144',
      label: '防盗门'
    }, {
      value: '145',
      label: '塑钢门窗'
    }, {
      value: '146',
      label: '铝合金、断桥铝门窗'
    }, {
      value: '147',
      label: '幕墙'
    }, {
      value: '148',
      label: '窗帘及其配件'
    }, {
      value: '149',
      label: '人防门'
    }, {
      value: '150',
      label: '门窗五金'
    }, {
      value: '151',
      label: '其他门窗'
    }, {
      value: '152',
      label: '卷帘'
    }]
  }, {
    value: '25',
    label: '墙砖 地砖 地板 地毯类材料',
    children: [{
      value: '153',
      label: '瓷砖'
    }, {
      value: '154',
      label: '马赛克'
    }, {
      value: '155',
      label: '瓷砖配件'
    }, {
      value: '156',
      label: '其他面砖'
    }, {
      value: '157',
      label: '实木地板'
    }, {
      value: '158',
      label: '复合地板'
    }, {
      value: '159',
      label: '防静电地板'
    }, {
      value: '160',
      label: '踢脚'
    }, {
      value: '161',
      label: '塑料地板'
    }, {
      value: '162',
      label: '地毯'
    }, {
      value: '163',
      label: '环氧地坪'
    }, {
      value: '164',
      label: '橡胶地板'
    }, {
      value: '165',
      label: '其他地面材料'
    }]
  }, {
    value: '26',
    label: '装饰辅材',
    children: [{
      value: '166',
      label: '轻钢龙骨'
    }, {
      value: '167',
      label: '烤漆龙骨'
    }, {
      value: '168',
      label: '铝合金龙骨'
    }, {
      value: '169',
      label: '线条'
    }, {
      value: '170',
      label: '木龙骨'
    }, {
      value: '171',
      label: '龙骨配件'
    }, {
      value: '172',
      label: '防腐木'
    }, {
      value: '173',
      label: '装饰件'
    }, {
      value: '174',
      label: '栏杆、扶手'
    }, {
      value: '175',
      label: '旗杆'
    }, {
      value: '176',
      label: '装饰字'
    }, {
      value: '177',
      label: '橱柜'
    }, {
      value: '178',
      label: '招牌、灯箱'
    }, {
      value: '179',
      label: '台类、货架'
    }, {
      value: '180',
      label: '其他装饰材料'
    }]
  }, {
    value: '27',
    label: '涂料',
    children: [{
      value: '181',
      label: '内墙涂料'
    }, {
      value: '182',
      label: '真石漆'
    }, {
      value: '183',
      label: '氟碳漆'
    }, {
      value: '184',
      label: '硅藻泥'
    }, {
      value: '185',
      label: '防火涂料'
    }, {
      value: '186',
      label: '防水涂料'
    }, {
      value: '187',
      label: '木器涂料'
    }, {
      value: '188',
      label: '功能涂料'
    }, {
      value: '189',
      label: '涂料辅助'
    }, {
      value: '190',
      label: '外墙涂料'
    }, {
      value: '191',
      label: '艺术涂料'
    }, {
      value: '192',
      label: '其他涂料'
    }]
  }, {
    value: '28',
    label: '石材',
    children: [{
      value: '193',
      label: '花岗岩'
    }, {
      value: '194',
      label: '大理石'
    }, {
      value: '195',
      label: '砂岩'
    }, {
      value: '196',
      label: '青石板'
    }, {
      value: '197',
      label: '文化石'
    }, {
      value: '198',
      label: '人造石'
    }, {
      value: '199',
      label: '水磨石'
    }, {
      value: '200',
      label: '石材制品'
    }, {
      value: '201',
      label: '石材配套'
    }]
  }, {
    value: '29',
    label: '墙面、天棚材料',
    children: [{
      value: '202',
      label: '石膏板'
    }, {
      value: '203',
      label: '胶合板'
    }, {
      value: '204',
      label: '细木地板'
    }, {
      value: '205',
      label: '水泥装饰板'
    }, {
      value: '206',
      label: '木质装饰板'
    }, {
      value: '207',
      label: '木质吸音板'
    }, {
      value: '208',
      label: '木质花格'
    }, {
      value: '209',
      label: '铝单板'
    }, {
      value: '210',
      label: '金箔、银箔'
    }, {
      value: '211',
      label: '铝塑板'
    }, {
      value: '212',
      label: '铝扣板'
    }, {
      value: '213',
      label: '壁布'
    }, {
      value: '214',
      label: '隔断'
    }, {
      value: '215',
      label: '矿棉板'
    }, {
      value: '216',
      label: '其他墙面材料'
    }, {
      value: '217',
      label: '格栅吊顶'
    }, {
      value: '218',
      label: '硅酸钙板'
    }, {
      value: '219',
      label: '集成吊顶'
    }, {
      value: '220',
      label: '阳关板'
    }, {
      value: '221',
      label: '壁纸'
    }, {
      value: '222',
      label: '不锈钢装饰板'
    }]
  }]
}, {
  value: '3',
  label: '辅材、工具',
  children: [{
    value: '30',
    label: '土建辅材',
    children: [{
      value: '223',
      label: '灰浆'
    }, {
      value: '224',
      label: '水泥浆'
    }, {
      value: '225',
      label: '石子浆'
    }, {
      value: '226',
      label: '油石、砂瓦'
    }, {
      value: '227',
      label: '木制容器类'
    }, {
      value: '228',
      label: '轴承'
    }, {
      value: '229',
      label: '纱网'
    }, {
      value: '230',
      label: '铁丝'
    }, {
      value: '231',
      label: '铁件'
    }, {
      value: '232',
      label: '小五金'
    }, {
      value: '233',
      label: '其他木制品'
    }, {
      value: '234',
      label: '其他五金件'
    }]
  }, {
    value: '31',
    label: '焊接材料',
    children: [{
      value: '235',
      label: '焊条'
    }, {
      value: '236',
      label: '焊丝'
    }, {
      value: '237',
      label: '焊剂、焊粉'
    }, {
      value: '238',
      label: '钎料及钎剂'
    }]
  }, {
    value: '32',
    label: '耗材/劳保',
    children: [{
      value: '239',
      label: '纸、笔'
    }, {
      value: '240',
      label: '劳保用品'
    }, {
      value: '241',
      label: '低值易耗品'
    }, {
      value: '242',
      label: '无损探伤用耗材'
    }]
  }, {
    value: '33',
    label: '磨具/磨料',
    children: [{
      value: '243',
      label: '砂轮'
    }, {
      value: '244',
      label: '磨头'
    }, {
      value: '245',
      label: '涂附磨具与磨料'
    }, {
      value: '246',
      label: '塑钢门窗'
    }, {
      value: '247',
      label: '铝合金、断桥铝门窗 幕墙'
    }, {
      value: '248',
      label: '窗帘及其配件'
    }, {
      value: '249',
      label: '人防门'
    }, {
      value: '250',
      label: '卷帘'
    }, {
      value: '251',
      label: '门窗五金'
    }, {
      value: '252',
      label: '其他门窗'
    }]
  }, {
    value: '34',
    label: '油品及胶粘材料',
    children: [{
      value: '253',
      label: '润滑油'
    }, {
      value: '254',
      label: '燃油料'
    }, {
      value: '255',
      label: '化工原料'
    }, {
      value: '256',
      label: '化工剂、化工填料'
    }, {
      value: '257',
      label: '润滑脂、蜡'
    }, {
      value: '258',
      label: '润剂油、绝缘油'
    }, {
      value: '259',
      label: '工业气体'
    }, {
      value: '260',
      label: '其他油品'
    }, {
      value: '261',
      label: '油料、树脂'
    }, {
      value: '262',
      label: '颜料、填料'
    }, {
      value: '263',
      label: '胶粘剂'
    }, {
      value: '264',
      label: '胶粘制品'
    }, {
      value: '265',
      label: '密封材料'
    }, {
      value: '266',
      label: '防水油膏、剂、粉、胶类'
    }]
  }, {
    value: '35',
    label: '检测仪器',
    children: [{
      value: '267',
      label: '工程测绘仪器'
    }, {
      value: '268',
      label: '电工测量仪表'
    }, {
      value: '269',
      label: '多功能强度检测仪'
    }, {
      value: '270',
      label: '全站型电子速测仪'
    }, {
      value: '271',
      label: '惯入式砂浆强度检测仪'
    }, {
      value: '272',
      label: '钢筋位置检测仪'
    }, {
      value: '273',
      label: '超声波检测仪'
    }]
  }]
}
]
export default option
